services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    image: docker-mon:latest
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - BASE_DIR=${BASE_DIR}
    volumes:
      - ../../docker:/usr/src/app/docker
      - /var/run/docker.sock:/var/run/docker.sock
    command: npm run start
