services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    image: docker-mon:dev
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}" # Backend port
      - "3001:3001"       # Frontend port
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - BASE_DIR=${BASE_DIR}
    volumes:
      - .:/usr/src/app           # Mount the source code for hot-reloading
      - /usr/src/app/node_modules # To avoid overwriting node_modules
      - ../../docker:/usr/src/app/docker
      - /var/run/docker.sock:/var/run/docker.sock
    command: npm run dev         # Use the dev command to run backend & frontend together
